Numpy

can be used to store data of diffrent forms: 1-d, 2-d, 3-d

can be used to computation and operation single and multi-dimensional array of elements

np.ndim => for checking dimensional array

np.array => creating a x dimensional array

np.len => get a length of array

np.shape => get how many rows

np[x,y] => to get an index of array elements

np[:, x] => will get a specific columns

np.zeros((x,y)) => will create a x dimensional array with 0 value

np.ones((x,y)) => will create a x dimensional array with 1 value

np.full((x,y), z, dtype) => will create a x dimensional array with constant variable 

np.random.rand((x,y)) => will create a matrix with a random value (dtype = float)

np.random.randint(range, ,size(x,y) )=> will create a matrix with a random value (dtype=int) and have range value

In [14]:
import numpy as np

In [21]:
## numpy 1d array
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

## numpy 2d array
arr2 = np.array([[1,2,3], [3,2,1]], dtype=np.int32)
print("2D Array:\n", arr2)

print("arr has : ", arr.shape)
print("arr2 has: ", arr2.shape)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [3 2 1]]
arr has :  (5,)
arr2 has:  (2, 3)


In [25]:
exmp_arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(exmp_arr[1,-1])

12


In [26]:
exmp_arr[:, 2]

array([3, 9])

In [27]:
np.zeros((2,2), dtype=np.int32)

array([[0, 0],
       [0, 0]], dtype=int32)

In [29]:
np.ones((3,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [30]:
np.full((2,2), 12, dtype=np.int32)

array([[12, 12],
       [12, 12]], dtype=int32)

In [31]:
np.random.rand(2,2)

array([[0.500109  , 0.4476042 ],
       [0.77079823, 0.60596214]])

In [34]:
np.random.randint(1,100, size=(2,10))

array([[55, 43, 11, 52, 45, 67, 57, 52, 36, 16],
       [96, 57, 90, 10, 95, 32, 45, 25, 91, 43]], dtype=int32)

In [54]:
test_arr = np.array([[1,2,3,4,6,7],
                     [5,6,7,8,9,9],
                     [9,10,11,12,13,13],
                     [13,14,15,16,17,17],
                     [17,18,19,20,21,21]])
test_arr[:3, -5:]

array([[ 2,  3,  4,  6,  7],
       [ 6,  7,  8,  9,  9],
       [10, 11, 12, 13, 13]])

In [84]:
n = 5

matrix = np.zeros((n,n) , dtype=np.int32)

matrix[n//2, :] = 1
matrix[:, n//2] = 1
matrix

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int32)